from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class PublicSource:
    source_id: str
    title: str
    url: str
    source_type: str
    route_family: str
    expected_answer: str
    fallback_text: str
    notes: str = ""


def public_sources() -> list[PublicSource]:
    """Return the small reproducible public-source registry.

    The URLs are real public pages. Fallback snapshots keep the benchmark usable
    offline after first setup or when a classroom network blocks fetching.
    """
    return [
        PublicSource(
            "pub_rfc_7231",
            "RFC 7231 HTTP Semantics and Content",
            "https://www.rfc-editor.org/rfc/rfc7231.txt",
            "rfc",
            "bm25",
            "HTTP/1.1 Semantics and Content",
            "RFC-7231 is titled Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content. "
            "It defines HTTP methods, status code semantics, request semantics, and response semantics.",
        ),
        PublicSource(
            "pub_rfc_9110",
            "RFC 9110 HTTP Semantics",
            "https://www.rfc-editor.org/rfc/rfc9110.txt",
            "rfc",
            "bm25",
            "HTTP Semantics",
            "RFC-9110 is titled HTTP Semantics. It revises and consolidates HTTP semantic definitions.",
        ),
        PublicSource(
            "pub_rfc_7235",
            "RFC 7235 HTTP Authentication",
            "https://www.rfc-editor.org/rfc/rfc7235.txt",
            "rfc",
            "bm25",
            "HTTP/1.1 Authentication",
            "RFC-7235 defines Hypertext Transfer Protocol (HTTP/1.1): Authentication. "
            "It describes HTTP authentication framework behavior and challenges.",
        ),
        PublicSource(
            "pub_rfc_3986",
            "RFC 3986 URI Generic Syntax",
            "https://www.rfc-editor.org/rfc/rfc3986.txt",
            "rfc",
            "bm25",
            "Uniform Resource Identifier generic syntax",
            "RFC-3986 defines Uniform Resource Identifier (URI): Generic Syntax. It covers URI syntax and components.",
        ),
        PublicSource(
            "pub_hipaa_164_512",
            "45 CFR 164.512 Uses and Disclosures",
            "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-E/section-164.512",
            "official_regulation",
            "bm25",
            "uses and disclosures for which authorization or opportunity to agree or object is not required",
            "45 CFR 164.512 covers uses and disclosures for which an authorization or opportunity to agree or object "
            "is not required. It is distinct from 164.510 and 164.514.",
        ),
        PublicSource(
            "pub_hipaa_164_510",
            "45 CFR 164.510 Uses Requiring Opportunity To Agree Or Object",
            "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-E/section-164.510",
            "official_regulation",
            "bm25",
            "uses and disclosures requiring an opportunity to agree or object",
            "45 CFR 164.510 covers uses and disclosures requiring an opportunity for the individual to agree or object.",
        ),
        PublicSource(
            "pub_icd_j18_9",
            "ICD-10 J18.9 Pneumonia Unspecified Organism",
            "https://icd.codes/icd10cm/J189",
            "medical_reference",
            "bm25",
            "pneumonia unspecified organism",
            "ICD-10-CM code J18.9 identifies pneumonia, unspecified organism. Nearby codes include J18.0 and J18.1.",
        ),
        PublicSource(
            "pub_torch_cross_entropy",
            "PyTorch torch.nn.CrossEntropyLoss",
            "https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html",
            "official_docs",
            "bm25",
            "criterion that computes cross entropy loss",
            "torch.nn.CrossEntropyLoss is a PyTorch criterion that computes cross entropy loss between logits and targets. "
            "It is different from torch.nn.NLLLoss and torch.nn.BCELoss.",
        ),
        PublicSource(
            "pub_numpy_svd",
            "NumPy numpy.linalg.svd",
            "https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html",
            "official_docs",
            "bm25",
            "singular value decomposition",
            "numpy.linalg.svd computes the singular value decomposition of an array.",
        ),
        PublicSource(
            "pub_postgres_jsonb",
            "PostgreSQL JSONB",
            "https://www.postgresql.org/docs/current/datatype-json.html",
            "official_docs",
            "bm25",
            "binary JSON data type",
            "PostgreSQL jsonb stores JSON data in a decomposed binary format that supports indexing and efficient querying.",
        ),
        PublicSource(
            "pub_python_dataclass",
            "Python dataclasses",
            "https://docs.python.org/3/library/dataclasses.html",
            "official_docs",
            "bm25",
            "decorator and functions for automatically adding generated special methods",
            "Python dataclasses provide a decorator and functions for automatically adding generated special methods to classes.",
        ),
        PublicSource(
            "pub_sklearn_tfidf",
            "scikit-learn TfidfVectorizer",
            "https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html",
            "official_docs",
            "bm25",
            "convert raw documents to a matrix of TF-IDF features",
            "sklearn.feature_extraction.text.TfidfVectorizer converts raw documents to a matrix of TF-IDF features.",
        ),
        PublicSource(
            "pub_climate_anxiety",
            "Climate Anxiety",
            "https://en.wikipedia.org/wiki/Climate_anxiety",
            "wikipedia",
            "dense",
            "climate anxiety",
            "Climate anxiety describes distress, worry, fear, or grief connected to climate change and environmental loss.",
        ),
        PublicSource(
            "pub_photosynthesis",
            "Photosynthesis",
            "https://en.wikipedia.org/wiki/Photosynthesis",
            "wikipedia",
            "dense",
            "photosynthesis",
            "Photosynthesis is the biological process by which plants, algae, and some bacteria convert light energy into chemical energy.",
        ),
        PublicSource(
            "pub_urban_heat_island",
            "Urban Heat Island",
            "https://en.wikipedia.org/wiki/Urban_heat_island",
            "wikipedia",
            "dense",
            "urban heat island",
            "An urban heat island is an urban area that is significantly warmer than nearby rural areas because surfaces store heat.",
        ),
        PublicSource(
            "pub_memory_consolidation",
            "Memory Consolidation",
            "https://en.wikipedia.org/wiki/Memory_consolidation",
            "wikipedia",
            "dense",
            "memory consolidation",
            "Memory consolidation is the process by which a temporary memory becomes more stable and durable over time.",
        ),
        PublicSource(
            "pub_algorithmic_bias",
            "Algorithmic Bias",
            "https://en.wikipedia.org/wiki/Algorithmic_bias",
            "wikipedia",
            "dense",
            "algorithmic bias",
            "Algorithmic bias describes systematic and repeatable errors in computer systems that create unfair outcomes.",
        ),
        PublicSource(
            "pub_circadian_rhythm",
            "Circadian Rhythm",
            "https://en.wikipedia.org/wiki/Circadian_rhythm",
            "wikipedia",
            "dense",
            "circadian rhythm",
            "A circadian rhythm is an internal biological process that follows a roughly 24-hour cycle.",
        ),
        PublicSource(
            "pub_reinforcement_learning",
            "Reinforcement Learning",
            "https://en.wikipedia.org/wiki/Reinforcement_learning",
            "wikipedia",
            "dense",
            "reinforcement learning",
            "Reinforcement learning is an area of machine learning where an agent learns behavior from rewards and penalties.",
        ),
        PublicSource(
            "pub_circular_economy",
            "Circular Economy",
            "https://en.wikipedia.org/wiki/Circular_economy",
            "wikipedia",
            "dense",
            "circular economy",
            "A circular economy aims to keep products and materials in use and reduce waste through reuse and recycling.",
        ),
        PublicSource(
            "pub_water_cycle",
            "Water Cycle",
            "https://en.wikipedia.org/wiki/Water_cycle",
            "wikipedia",
            "dense",
            "water cycle",
            "The water cycle describes the continuous movement of water through evaporation, condensation, precipitation, and runoff.",
        ),
        PublicSource(
            "pub_allergy",
            "Allergy",
            "https://en.wikipedia.org/wiki/Allergy",
            "wikipedia",
            "dense",
            "allergy",
            "An allergy is an immune system reaction to a foreign substance that is usually harmless to most people.",
        ),
        PublicSource(
            "pub_diffusion_innovations",
            "Diffusion of Innovations",
            "https://en.wikipedia.org/wiki/Diffusion_of_innovations",
            "wikipedia",
            "dense",
            "diffusion of innovations",
            "Diffusion of innovations explains how new ideas, technologies, or practices spread through a social system.",
        ),
        PublicSource(
            "pub_distributional_semantics",
            "Distributional Semantics",
            "https://en.wikipedia.org/wiki/Distributional_semantics",
            "wikipedia",
            "dense",
            "distributional semantics",
            "Distributional semantics represents meaning from the contexts in which words appear.",
        ),
        PublicSource(
            "pub_bat",
            "Bat",
            "https://en.wikipedia.org/wiki/Bat",
            "wikipedia",
            "kg",
            "bat is a mammal",
            "A bat is a mammal. Bats are vertebrates and are capable of powered flight using wings and echolocation.",
        ),
        PublicSource(
            "pub_penguin",
            "Penguin",
            "https://en.wikipedia.org/wiki/Penguin",
            "wikipedia",
            "kg",
            "penguin is a bird",
            "A penguin is a bird. Penguins are vertebrates and are not capable of flight but are capable of swimming.",
        ),
        PublicSource(
            "pub_dolphin",
            "Dolphin",
            "https://en.wikipedia.org/wiki/Dolphin",
            "wikipedia",
            "kg",
            "dolphin is a mammal",
            "A dolphin is a mammal. Dolphins are vertebrates that produce milk and are capable of swimming.",
        ),
        PublicSource(
            "pub_whale",
            "Whale",
            "https://en.wikipedia.org/wiki/Whale",
            "wikipedia",
            "kg",
            "whale is a mammal",
            "A whale is a mammal. Whales are vertebrates that produce milk and are capable of swimming.",
        ),
        PublicSource(
            "pub_salmon",
            "Salmon",
            "https://en.wikipedia.org/wiki/Salmon",
            "wikipedia",
            "kg",
            "salmon is a fish",
            "A salmon is a fish. Salmon are vertebrates and are capable of swimming.",
        ),
        PublicSource(
            "pub_mosquito",
            "Mosquito",
            "https://en.wikipedia.org/wiki/Mosquito",
            "wikipedia",
            "kg",
            "mosquito is an insect",
            "A mosquito is an insect. Mosquitoes have wings and are capable of flying.",
        ),
        PublicSource(
            "pub_ostrich",
            "Ostrich",
            "https://en.wikipedia.org/wiki/Ostrich",
            "wikipedia",
            "kg",
            "ostrich is a bird",
            "An ostrich is a bird. Ostriches are vertebrates and are not capable of flight.",
        ),
        PublicSource(
            "pub_eagle",
            "Eagle",
            "https://en.wikipedia.org/wiki/Eagle",
            "wikipedia",
            "kg",
            "eagle is a bird",
            "An eagle is a bird. Eagles are vertebrates and are capable of flying.",
        ),
        PublicSource(
            "pub_frog",
            "Frog",
            "https://en.wikipedia.org/wiki/Frog",
            "wikipedia",
            "kg",
            "frog is a vertebrate",
            "A frog is an amphibian and a vertebrate. Frogs can swim and jump.",
        ),
        PublicSource(
            "pub_mammal",
            "Mammal",
            "https://en.wikipedia.org/wiki/Mammal",
            "wikipedia",
            "kg",
            "mammal is an animal",
            "A mammal is a vertebrate animal. Mammals produce milk and include bats, dolphins, whales, cats, and dogs.",
        ),
        PublicSource(
            "pub_bird",
            "Bird",
            "https://en.wikipedia.org/wiki/Bird",
            "wikipedia",
            "kg",
            "bird is a vertebrate",
            "A bird is a warm-blooded vertebrate animal. Birds include penguins, eagles, owls, ducks, and sparrows.",
        ),
        PublicSource(
            "pub_vertebrate",
            "Vertebrate",
            "https://en.wikipedia.org/wiki/Vertebrate",
            "wikipedia",
            "kg",
            "vertebrate is an animal",
            "A vertebrate is an animal with a backbone or spinal column. Mammals, birds, fish, amphibians, and reptiles are vertebrates.",
        ),
        PublicSource(
            "pub_bat_echolocation",
            "Bat Echolocation",
            "https://en.wikipedia.org/wiki/Animal_echolocation#Bats",
            "wikipedia",
            "hybrid",
            "echolocation",
            "Bats use echolocation and wings. A bat connects to vertebrate through mammal, and echolocation helps bats navigate.",
        ),
        PublicSource(
            "pub_penguin_swimming",
            "Penguin Swimming",
            "https://en.wikipedia.org/wiki/Penguin#Anatomy_and_physiology",
            "wikipedia",
            "hybrid",
            "swimming",
            "Penguins are birds and vertebrates. Their flippers and streamlined bodies connect penguins to swimming rather than flight.",
        ),
        PublicSource(
            "pub_dolphin_mammal_swim",
            "Dolphin Mammal Swimming",
            "https://en.wikipedia.org/wiki/Dolphin#Anatomy",
            "wikipedia",
            "hybrid",
            "mammal",
            "A dolphin connects to vertebrate through mammal. Text evidence also describes dolphins as aquatic mammals capable of swimming.",
        ),
        PublicSource(
            "pub_salmon_fish_migration",
            "Salmon Fish Migration",
            "https://en.wikipedia.org/wiki/Salmon_run",
            "wikipedia",
            "hybrid",
            "fish",
            "Salmon connect to vertebrate through fish. Public text describes salmon migration and swimming in river and ocean habitats.",
        ),
        PublicSource(
            "pub_mosquito_insect_flight",
            "Mosquito Insect Flight",
            "https://en.wikipedia.org/wiki/Mosquito#Anatomy",
            "wikipedia",
            "hybrid",
            "insect",
            "A mosquito connects to animal through insect. Text evidence describes mosquito wings and flight.",
        ),
        PublicSource(
            "pub_ostrich_bird_counterexample",
            "Ostrich Bird Counterexample",
            "https://en.wikipedia.org/wiki/Ostrich",
            "wikipedia",
            "hybrid",
            "bird",
            "An ostrich connects to vertebrate through bird, but it is a flightless bird and a counterexample for all birds fly.",
        ),
        PublicSource(
            "pub_eagle_bird_flight",
            "Eagle Bird Flight",
            "https://en.wikipedia.org/wiki/Eagle",
            "wikipedia",
            "hybrid",
            "bird",
            "An eagle connects to vertebrate through bird. Text evidence describes eagle wings and flight.",
        ),
        PublicSource(
            "pub_whale_mammal_milk",
            "Whale Mammal Milk",
            "https://en.wikipedia.org/wiki/Whale",
            "wikipedia",
            "hybrid",
            "mammal",
            "A whale connects to vertebrate through mammal. Text evidence describes whales as mammals that produce milk.",
        ),
        PublicSource(
            "pub_frog_vertebrate_amphibian",
            "Frog Amphibian Vertebrate",
            "https://en.wikipedia.org/wiki/Frog",
            "wikipedia",
            "hybrid",
            "vertebrate",
            "A frog connects to animal through vertebrate. Text evidence describes frogs as amphibians with backbones.",
        ),
        PublicSource(
            "pub_duck_bird_swim",
            "Duck Bird Swimming",
            "https://en.wikipedia.org/wiki/Duck",
            "wikipedia",
            "hybrid",
            "bird",
            "A duck connects to vertebrate through bird. Text evidence describes ducks as birds that can swim.",
        ),
        PublicSource(
            "pub_cat_mammal_pet",
            "Cat Mammal",
            "https://en.wikipedia.org/wiki/Cat",
            "wikipedia",
            "hybrid",
            "mammal",
            "A cat connects to vertebrate through mammal. Text evidence describes cats as small carnivorous mammals.",
        ),
        PublicSource(
            "pub_owl_bird_predator",
            "Owl Bird",
            "https://en.wikipedia.org/wiki/Owl",
            "wikipedia",
            "hybrid",
            "bird",
            "An owl connects to vertebrate through bird. Text evidence describes owls as birds of prey with wings.",
        ),
    ]


def sources_by_id() -> dict[str, PublicSource]:
    return {source.source_id: source for source in public_sources()}
